server.port=8080
spring.application.name=little-note-backend
spring.config.import=optional:file:./.env[.properties]

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/littlenote}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
